### ISSUE TITLE
Issue when running vivi function with xgboost

### ISSUE THREAD

**Issue by ghost** [AlanInglis/vividPackage#3]
Hello Mr. (Dr.?) Inglis:

I am really looking forward to working with your package.

I am trying to run VIVID with a xgboost machine learning model. I am following your excellent directions. However, I am getting the following error when I try to run vivi

pFun <- function(fit, data, ...) predict(fit, as.matrix(dataset_oh_1[,2:19]))
> set.seed(1701)
> dataset_oh <- as_tibble(dataset_oh)
> set.seed(1701)
> viviGBst <- vivi(fit = gbst,
+                  data = dataset_oh,
+                  response = "LOS",
+                  reorder = FALSE,
+                  normalized = FALSE,
+                  predictFun = pFun)
Agnostic variable importance method used.
Calculating interactions...
Error in `[[<-`:
! Assigned data `stats::predict(x, data = X[, cols, drop = FALSE])` must be compatible with
  existing data.
✖ Existing data has 25000 rows.
✖ Assigned data has 10792 rows.
ℹ Only vectors of size 1 are recycled.
Caused by error in `vectbl_recycle_rhs_rows()`:
! Can't recycle input of size 10792 to size 25000.
Run `rlang::last_trace()` to see where the error occurred.

Here is the backtrace:

 1. └─vivid::vivi(...)
  2.   ├─vivid:::vividInteraction(...)
  3.   └─vivid:::vividInteraction.default(...)
  4.     ├─flashlight::light_interaction(...)
  5.     └─flashlight:::light_interaction.flashlight(...)
  6.       └─flashlight (local) core_func(data)
  7.         └─base::lapply(v, statistic, dat = X, grid_id = grid_id)
  8.           └─flashlight (local) FUN(X[[i]], ...)
  9.             └─flashlight (local) call_pd(dat, z = z, gid = grid_id)
 10.               ├─base::`[[<-`(`*tmp*`, vn, value = `<dbl>`)
 11.               └─tibble:::`[[<-.tbl_df`(`*tmp*`, vn, value = `<dbl>`)
 12.                 └─tibble:::tbl_subassign(...)
 13.                   └─tibble:::vectbl_recycle_rhs_rows(value, fast_nrow(xo), i_arg = NULL, value_arg, call)

Someone on Stackoverflow has the same issue, but I can't find it. Sorry.

**Comment by ghost** [comment]
Here is the stackoverflow issue:

https://stackoverflow.com/questions/74338823/getting-error-while-calculating-feature-importances-r

**Comment by AlanInglis** [comment]
Hi,

I've tracked down the cause of the issue. It is a side effect of how the internal predict function works in vivid. When creating the predict function, you must include the term "data" instead of the actual name of the name of the data. Below is a small example of how to recreate and solve the issue. 


```
#Load libraries:
library(vivid)
library(xgboost)

#Load data:
set.seed(1701)
aq <- na.omit(airquality)

#Create gbm:
gbst <- xgboost(
  data = as.matrix(aq[, 1:6]),
  label = as.matrix(aq[, 1]),
  nrounds = 100,
  verbose = 0
)

#Create predict function:
pFun <- function(fit, data, ...) predict(fit, as.matrix(data[, 1:6]))

#NOTE: In the predict function above, you must use the term 'data' in the function 
#argument (i.e., do not use the actual name of the data!). You must also include
#the response variable.

#Run vivid:
set.seed(1701)
viviGBst <- vivi(
  fit = gbst,
  data = aq,
  response = "Ozone",
  reorder = FALSE,
  normalized = FALSE,
  predictFun = pFun
)

#Output:
viviGBst


#-------------------------------------------------------------------------

#Recreating the error:
pFun <- function(fit, data, ...) predict(fit, as.matrix(aq[, 1:6])) # used 'aq' instead of 'data'

#Run vivid:
viviGBst <- vivi(
  fit = gbst,
  data = aq,
  response = "Ozone",
  predictFun = pFun
)
```


Hopefully that solves the problem. But let me know if you're still having any issues!

**Comment by ghost** [comment]
Mr. (Dr) Inglis:

THANK YOU For the very quick response! I am grateful for your help.

I will run this code soon and share results.

Take care,

Brian

**Comment by ghost** [comment]
Thank you for your help.

I've included the plot VIVID made with your help.

**Comment by markhwhiteii** [comment]
I am getting an error here, despite following the solution above. Mine is a little bit more complicated than the example above, because all of my columns are categorical. Thus, I have to dummy-code them before putting them into `xgboost()`.

I remove NAs and then limit my data to the `cand_vars` that will be candidate predictor variables, and then I add back the outcome variable by `cbind()` it to the end:

```
  data <- na.omit(data)
  mat <- model.matrix.lm(~ . - 1, data = data[unique(cand_vars)])
  mat <- cbind(mat, age_match = data$age_match)
```

Then I fit the model, following a `seed`:

```
  set.seed(seed)
  # vanilla xgb
  mod <- xgboost::xgboost(
    mat[, 1:(ncol(mat) - 1)],
    mat[, ncol(mat)],
    nrounds = 50,
    params = list(objective = "binary:logistic"),
    verbose = 0
  )
```

This programs the wrapper function I'm making such that it always considers the last variable the outcome.

I define the prediction function and pass to `vivi`:

```
pfun <- function(fit, data) {
    predict(fit, data[, 1:(ncol(data) - 1)])
  }
  
  vivid::vivi(
    fit = mod,
    data = mat,
    response = "age_match",
    predictFun = pfun
  )
```

And yet I get:

```
Error in data[[response]] : subscript out of bounds
```

This is because the `data[[response]]` syntax to pull out a variable is not valid for a matrix.

**Comment by markhwhiteii** [comment]
Figured it out. For anyone wondering, I had to do some awkward coercing of matrix to data.frame to back to matrix:

```
  data <- na.omit(data)
  mat <- model.matrix.lm(~ . - 1, data = data[unique(cand_vars)])
  mat <- cbind(mat, age_match = data$age_match)
  mat <- as.data.frame(mat)
  
  set.seed(seed)
  # vanilla xgb
  mod <- xgboost::xgboost(
    as.matrix(mat[, 1:(ncol(mat) - 1)]),
    as.matrix(mat[, ncol(mat)]),
    nrounds = 50,
    params = list(objective = "binary:logistic"),
    verbose = 0
  )
  
  pfun <- function(fit, data, ...) {
    predict(fit, as.matrix(data[, 1:(ncol(data) - 1)]))
  }
  
  vivid::vivi(
    fit = mod,
    data = mat,
    response = "age_match",
    predictFun = pfun
  )
```

**Comment by AlanInglis** [comment]
Hi Mark. Glad you fixed the issue. I think you could have solved it by just passing the matrix as a dataframe into the `vivid::vivi()` function. So, something like this: 

`vivid::vivi(
    fit = mod,
    data = as.data.frame(mat),
    response = "age_match",
    predictFun = pfun
  )`


I have added a small example below using fake data that I think recreates your issue with the quick solution. 

```
library(xgboost)
library(vivid)

# --- Example dataset
set.seed(1701)
n <- 200
df <- data.frame(
  colour = sample(c("red", "blue", "green"), n, replace = TRUE),
  size   = sample(c("small", "medium", "large"), n, replace = TRUE),
  shape  = sample(c("circle", "square"), n, replace = TRUE),
  region = sample(c("north", "south", "east", "west"), n, replace = TRUE),
  age_match = sample(c(0, 1), n, replace = TRUE)
)

# --- Candidate variables (all predictors)
cand_vars <- c("colour", "size", "shape", "region")

# --- Remove NAs (none here, but just to match the example @markhwhiteii provided above)
df <- na.omit(df)

# --- Dummy coding of categorical predictors 
mat <- model.matrix.lm(~ . - 1, data = df[unique(cand_vars)])

# --- Add outcome as last column 
mat <- cbind(mat, age_match = df$age_match)

# --- Fit XGBoost model
set.seed(1701)
mod <- xgboost(
  data = mat[, 1:ncol(mat) - 1],
  label = mat[, ncol(mat)],
  nrounds = 50,
  params = list(objective = "binary:logistic"),
  verbose = 0
)

# --- Prediction function for vivi
pfun <- function(fit, data,...) {
  predict(fit, as.matrix(data[, 1:ncol(data) - 1]))
}

# --- Vivid variable importance ---
res <- vivid::vivi(
  fit = mod,
  data = as.data.frame(mat), # making the matrix a data frame for vivid
  response = "age_match",
  predictFun = pfun
)
```

I think everything is set up as in your example. But that should run: 

```
# --- Quick look at some of the results
res[1:3,1:3]
            shapesquare sizemedium  sizesmall
shapesquare  0.11990521 0.06858927 0.03152680
sizemedium   0.06858927 0.07622295 0.01201341
sizesmall    0.03152680 0.01201341 0.06246060
```
