### ISSUE TITLE
Error in `dplyr::bind_cols()`: ! Can't recycle `..1` (size 49) to match `..2` (size 50).

### ISSUE THREAD

**Issue by jielab** [AlanInglis/vividPackage#7]
Hi, there:

Please see the screenshot below. 
![image](https://github.com/AlanInglis/vivid/assets/26947455/46506162-4263-4a6b-9f4f-4d3b127ecafe)

Can you please let me know how to address this?

Thank you very much & best regards,
Jie

**Comment by jielab** [comment]
Hi, there: 

I figured this out. Basically my data can NOT contain any NA values.

Best regards,
jie

**Comment by AlanInglis** [comment]
Hi,

Since you have a solution, I'm closing this issue.
