### ISSUE TITLE
Reduce point size of lablels in network plot

### ISSUE THREAD

**Issue by bsdelavan** [AlanInglis/vividPackage#9]
Hello. Great package! I am working with a network plot, and I would like to reduce the size of the labels on the plot for readability. Is there a way to do this in the package? Thank you.

**Comment by AlanInglis** [comment]
Hi. This can be changed by manipulating the actual `ggplot` object that's created when plotting the network. The code below shows how to do it. In the code, I'm fitting a simple model and creating the network plot. Im then manually changing the label size by manipulating the actual network plot object. 

    library(vivid)
    library(randomForest)
    
    
    # get data
    aq <- na.omit(airquality)
    
    
    # Fit a random forest model
    rf <- randomForest(Ozone ~ ., data = aq)
    
    # get vivi matrix
    viviRf <- vivi(fit = rf, 
                   data = aq,
                   response = "Ozone")
    
    # plot netwrok with original sized labels
    viviPlot <- viviNetwork(mat = viviRf) 
    viviPlot # original label size
    
    
    
    # change label size -------------------------------------------------------
    
    # Access the layer of the plot that contains the labels (in this case layer 3)
    label_layer <- viviPlot$layers[[3]]
    
    # Change the size of the labels in the third layer
    label_layer$aes_params$size <- 2  # Set the desired label size
    
    # Reassign the modified layer back to the plot object
    viviPlot$layers[[3]] <- label_layer
    
    # Display the modified network plot with updated label sizes
    viviPlot`
